apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: pay-infra
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: pay-infra
  syncPolicy:
    automated:
      enabled: true
      prune: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
  sources:
  - repoURL: https://argoproj.github.io/argo-helm
    targetRevision: {{ .Values.argocd.version }}
    chart: argo-cd
    helm:
      valueFiles:
      - $repo/values/pay-infra/argocd/values.yaml
  - repoURL: 'https://github.com/govuk-pay/helm-charts.git'
    ref: repo
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
