---
apiVersion: v1
kind: Secret
metadata:
  name: localstack-aws-secret
stringData:
  creds: |
    [default]
    aws_access_key_id = test
    aws_secret_access_key = test
---
apiVersion: aws.m.upbound.io/v1beta1
kind: ClusterProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      name: localstack-aws-secret
      namespace: crossplane
      key: creds
  endpoint:
    hostnameImmutable: true
    services: [sqs, sns]
    url:
      type: Static
      static: http://localstack.localstack.svc.cluster.local:4566
  skip_credentials_validation: true
  skip_metadata_api_check: true
  s3_use_path_style: true
