env:
  BIND_HOST: 0.0.0.0
  RUN_MIGRATION: 'true'
  RUN_APP: 'true'
  DISABLE_INTERNAL_HTTPS: 'true'
  http_proxy: http://egress:8080
  HTTP_PROXY: http://egress:8080
  https_proxy: http://egress:8080
  HTTPS_PROXY: http://egress:8080
  HTTP_PROXY_HOST: egress
  HTTPS_PROXY_HOST: egress
  HTTP_PROXY_PORT: 8080
  HTTPS_PROXY_PORT: 8080
  HTTP_PROXY_URI: http://egress:8080
  HTTPS_PROXY_URI: http://egress:8080
  HTTP_PROXY_ENABLED: true
  HTTPS_PROXY_ENABLED: true
  HTTP_PROXY_SCHEME: http
  SECURE_COOKIE_OFF: true
  JAVA_OPTS: -Xms128m -Xmx1G