{{- if .Values.deployDatabase }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "pay-app.fullname" . }}-db
spec:
  instances: 1
  bootstrap:
    initdb:
      database: {{ include "pay-app.fullname" . }}
      owner: {{ include "pay-app.fullname" . }}
  postgresql:
    extensions:
    - name: uuid-ossp
    - name: pg_trgm
      schema: pg_catalog
  storage:
    size: 1Gi
{{- end }}