{{- if .Values.dockerPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pay-app.fullname" . }}-docker-password
type: kubernetes.io/dockercfg
data:
  .dockercfg: |
    {
      "auths": {
        "223851549868.dkr.ecr.eu-west-2.amazonaws.com": {
          "username": "AWS",
          "password": "{{ .Values.dockerPassword }}"
        }
      }
    }
{{- end }}
