apiVersion: sqs.aws.m.upbound.io/v1beta1
kind: Queue
metadata:
  name: connector_tasks_queue
  labels:
    {{- include "pay-cluster.labels" . | nindent 4 }}
spec:
  forProvider:
    delaySeconds: 0
    visibilityTimeout: 3600
    name: '{{ include "pay-cluster.fullname" . }}-connector_tasks_queue'
    receiveWaitTimeSeconds: 0
    region: eu-west-2
  writeConnectionSecretToRef:
    name: connector_tasks_queue
