{{- if .Values.useCrossplane }}
---
apiVersion: sqs.aws.m.upbound.io/v1beta1
kind: Queue
metadata:
  name: connector-tasks-queue
  labels:
    {{- include "pay-cluster.labels" . | nindent 4 }}
spec:
  forProvider:
    delaySeconds: 0
    visibilityTimeoutSeconds: 3600
    name: '{{ include "pay-cluster.fullname" . }}-connector_tasks_queue'
    receiveWaitTimeSeconds: 0
    region: eu-west-2
  writeConnectionSecretToRef:
    name: connector-tasks-queue
---
apiVersion: sqs.aws.m.upbound.io/v1beta1
kind: Queue
metadata:
  name: pay-capture-queue
  labels:
    {{- include "pay-cluster.labels" . | nindent 4 }}
spec:
  forProvider:
    delaySeconds: 0
    visibilityTimeoutSeconds: 3600
    name: '{{ include "pay-cluster.fullname" . }}-pay_capture_queue'
    receiveWaitTimeSeconds: 0
    region: eu-west-2
  writeConnectionSecretToRef:
    name: pay-capture-queue
---
apiVersion: sqs.aws.m.upbound.io/v1beta1
kind: Queue
metadata:
  name: pay-event-queue
  labels:
    {{- include "pay-cluster.labels" . | nindent 4 }}
spec:
  forProvider:
    delaySeconds: 0
    visibilityTimeoutSeconds: 3600
    name: '{{ include "pay-cluster.fullname" . }}-pay_event_queue'
    receiveWaitTimeSeconds: 0
    region: eu-west-2
  writeConnectionSecretToRef:
    name: pay-event-queue
---
apiVersion: sqs.aws.m.upbound.io/v1beta1
kind: Queue
metadata:
  name: payout-reconcile-queue
  labels:
    {{- include "pay-cluster.labels" . | nindent 4 }}
spec:
  forProvider:
    delaySeconds: 0
    visibilityTimeoutSeconds: 3600
    name: '{{ include "pay-cluster.fullname" . }}-payout_reconcile_queue'
    receiveWaitTimeSeconds: 0
    region: eu-west-2
  writeConnectionSecretToRef:
    name: payout-reconcile-queue
---
apiVersion: sqs.aws.m.upbound.io/v1beta1
kind: Queue
metadata:
  name: webhooks-events-subscriber-queue
  labels:
    {{- include "pay-cluster.labels" . | nindent 4 }}
spec:
  forProvider:
    delaySeconds: 0
    visibilityTimeoutSeconds: 3600
    name: '{{ include "pay-cluster.fullname" . }}-webhooks-events-subscriber-queue'
    receiveWaitTimeSeconds: 0
    region: eu-west-2
  writeConnectionSecretToRef:
    name: webhooks-events-subscriber-queue
{{- end }}
