apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: localstack
  namespace: argocd
spec:
  project: default
  source:
      repoURL: https://localstack.github.io/helm-charts
      targetRevision: 0.7.0
      chart: localstack
      helm:
        valuesObject:
          image:
            repository: localstack/locakstack
            tag: 4.14.0
  destination:
    server: "https://kubernetes.default.svc"
    namespace: localstack
  syncPolicy:
    automated:
      enabled: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
